default_language_version:
  # default language version for each language
    python: python3.9
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
        # See https://pre-commit.com/hooks.html for more hooks
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: pylint
        exclude: ^server/
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        exclude: ^server/
