# Generated by Django 4.2.3 on 2023-07-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.CharField(default='default description', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialization',
            name='on_homepage',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercounty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_county', to='api.user'),
        ),
    ]
