# Generated by Django 4.2.3 on 2023-10-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_ready_for_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=55)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_licenses', to='api.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='api.user')),
            ],
        ),
    ]
