# Generated by Django 4.2.3 on 2024-01-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_content_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.URLField(default='https://media.istockphoto.com/id/1352603244/photo/shot-of-an-unrecognizable-businessman-working-on-his-laptop-in-the-office.jpg?s=612x612&w=is&k=20&c=F-1ARGEM8US7lAwURWDAgRmprIN7lTwKbOMr-TDLolk='),
            preserve_default=False,
        ),
    ]
