# Generated by Django 4.2.1 on 2024-01-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_content_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
