# Generated by Django 4.2.1 on 2024-01-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_content_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=models.CharField(max_length=55),
        ),
    ]
