# Generated by Django 4.2.3 on 2024-01-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_content_image_alter_shopitem_image_and_more'),
        ('api', '0005_alter_content_slug'),
    ]

    operations = [
    ]
